services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app          # монтируем весь проект внутрь контейнера
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      WATCHFILES_FORCE_POLLING: "true"  # помогает отслеживать изменения на macOS/Windows в Docker

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: repair_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
