services:
  api:
    image: maxim7777ma/mini-crm-repair:latest
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: repair_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
